name: CURL-ACTION
  # You may pin to the exact commit or the version.
  # uses: enflo/curl-action@fabe347922c7a9e88bafa15c4b7d6326ea802695
  uses: enflo/curl-action@v1.2
  with:
    # curl arguments
    curl: # default is toniflorithomar.cat
